### ISSUE TITLE
Game crashes when rendering the Trident as an item entity - 1.19

### ISSUE THREAD

**Issue by equalizer32** [LukeGrahamLandry/inclusive-enchanting-mod#2]
[crash-2023-06-12_17.36.44-client.txt](https://github.com/LukeGrahamLandry/inclusive-enchanting-mod/files/11725286/crash-2023-06-12_17.36.44-client.txt)

This issue happens both with and without game renderer modifications.

**Comment by LukeGrahamLandry** [comment]
This is fixed in the latest release (1.2.19).

**Comment by equalizer32** [comment]
Oh sorry. I dind't notice that 1.2.19 was available on 1.19 since I use Modrinth.

**Comment by LukeGrahamLandry** [comment]
Ah! I’ll release it there as well. I always forget ;-;
